<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-10-27T12:55:34 PKT" name="Default suite" finished-at="2022-10-27T12:57:33 PKT" duration-ms="119044">
    <groups>
    </groups>
    <test started-at="2022-10-27T12:55:34 PKT" name="Default test" finished-at="2022-10-27T12:57:33 PKT" duration-ms="119044">
      <class name="Test.Test_Application_Stage_Rejected">
        <test-method is-config="true" signature="setup()[pri:0, instance:Test.Test_Application_Stage_Rejected@6cdba6dc]" started-at="2022-10-27T12:55:34 PKT" name="setup" finished-at="2022-10-27T12:55:46 PKT" duration-ms="11798" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="App_Create_Test_forms_Single_Section()[pri:1, instance:Test.Test_Application_Stage_Rejected@6cdba6dc]" started-at="2022-10-27T12:55:46 PKT" name="App_Create_Test_forms_Single_Section" finished-at="2022-10-27T12:56:27 PKT" duration-ms="40363" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- App_Create_Test_forms_Single_Section -->
        <test-method signature="Verifying_Multiple_Stages_with_Reject_Status_Randomly()[pri:2, instance:Test.Test_Application_Stage_Rejected@6cdba6dc]" started-at="2022-10-27T12:56:27 PKT" name="Verifying_Multiple_Stages_with_Reject_Status_Randomly" finished-at="2022-10-27T12:57:33 PKT" duration-ms="66543" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[did not expect [13] but found [13]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: did not expect [13] but found [13]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1399)
at org.testng.Assert.assertNotEquals(Assert.java:1404)
at Test.Test_Application_Stage_Rejected.Verifying_Multiple_Stages_with_Reject_Status_Randomly(Test_Application_Stage_Rejected.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Verifying_Multiple_Stages_with_Reject_Status_Randomly -->
        <test-method is-config="true" signature="Tear_Down()[pri:0, instance:Test.Test_Application_Stage_Rejected@6cdba6dc]" started-at="2022-10-27T12:57:33 PKT" name="Tear_Down" finished-at="2022-10-27T12:57:33 PKT" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tear_Down -->
      </class> <!-- Test.Test_Application_Stage_Rejected -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
